NEO4J_URI = "neo4j://127.0.0.1:7687"
NEO4J_USER = "neo4j"
NEO4J_PASSWORD = "your-password-here"
NEO4J_DATABASE = "neo4j"
MEDIA_ROOT = r"D:\gopher-brain-media"
ANTHROPIC_API_KEY = "your-key-here"
OPENAI_API_KEY = "your-key-here"
